import express from "express";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { pool } from "../db.js";
import { publicInternalError } from "../utils/publicError.js";
import { auditLog } from "../utils/auditLog.js";
import { exportExerciseCatalogueSnapshot } from "./adminExerciseCatalogue.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = join(__dirname, "../../migrations");

export const adminSyncRouter = express.Router();

// ── SQL literal helpers ────────────────────────────────────────────────────

function textLit(v) {
  if (v === null || v === undefined) return "NULL";
  return `'${String(v).replace(/'/g, "''")}'`;
}

function intLit(v) {
  if (v === null || v === undefined) return "NULL";
  const n = parseInt(v, 10);
  return Number.isFinite(n) ? String(n) : "NULL";
}

function boolLit(v) {
  return v ? "true" : "false";
}

function jsonbLit(v) {
  if (v === null || v === undefined) return "NULL";
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
}

function genTs() {
  return new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
}

function fileHeader(title, rowCount) {
  return [
    `-- ${title} — Full Snapshot`,
    `-- Auto-generated by Admin UI. DO NOT edit manually.`,
    `-- Generated: ${genTs()}`,
    `-- Row count: ${rowCount}`,
    ``,
  ].join("\n");
}

// ── Snapshot generators ────────────────────────────────────────────────────

async function generatePgcSnapshot(db) {
  const { rows } = await db.query(`
    SELECT config_key, program_type, schema_version, is_active, total_weeks_default, notes,
           program_generation_config_json, progression_by_rank_json, week_phase_config_json
    FROM public.program_generation_config
    ORDER BY config_key
  `);

  const inserts = rows.map((r) => `\
INSERT INTO public.program_generation_config (
  config_key, program_type, schema_version, is_active, total_weeks_default, notes,
  program_generation_config_json, progression_by_rank_json, week_phase_config_json, updated_at
) VALUES (
  ${textLit(r.config_key)},
  ${textLit(r.program_type)},
  ${intLit(r.schema_version)},
  ${boolLit(r.is_active)},
  ${intLit(r.total_weeks_default)},
  ${textLit(r.notes)},
  ${jsonbLit(r.program_generation_config_json)},
  ${jsonbLit(r.progression_by_rank_json)},
  ${jsonbLit(r.week_phase_config_json)},
  now()
)
ON CONFLICT (config_key) DO UPDATE SET
  program_type                   = EXCLUDED.program_type,
  schema_version                 = EXCLUDED.schema_version,
  is_active                      = EXCLUDED.is_active,
  total_weeks_default            = EXCLUDED.total_weeks_default,
  notes                          = EXCLUDED.notes,
  program_generation_config_json = EXCLUDED.program_generation_config_json,
  progression_by_rank_json       = EXCLUDED.progression_by_rank_json,
  week_phase_config_json         = EXCLUDED.week_phase_config_json,
  updated_at                     = EXCLUDED.updated_at;`);

  return {
    content: fileHeader("Program Generation Config", rows.length) + inserts.join("\n\n") + "\n",
    rows: rows.length,
  };
}

async function generateRepRulesSnapshot(db) {
  const { rows } = await db.query(`
    SELECT rule_id, program_type, schema_version, is_active, day_type, purpose,
           segment_type, movement_pattern, swap_group_id_1, swap_group_id_2, equipment_slug,
           rep_low, rep_high, reps_unit,
           rir_target, rir_min, rir_max,
           tempo_eccentric, tempo_pause_bottom, tempo_concentric, tempo_pause_top,
           rest_after_set_sec, rest_after_round_sec,
           logging_prompt_mode, notes_style, priority
    FROM public.program_rep_rule
    ORDER BY program_type, COALESCE(priority, 0) DESC, rule_id
  `);

  const inserts = rows.map((r) => `\
INSERT INTO public.program_rep_rule (
  rule_id, program_type, schema_version, is_active, day_type, purpose,
  segment_type, movement_pattern, swap_group_id_1, swap_group_id_2, equipment_slug,
  rep_low, rep_high, reps_unit,
  rir_target, rir_min, rir_max,
  tempo_eccentric, tempo_pause_bottom, tempo_concentric, tempo_pause_top,
  rest_after_set_sec, rest_after_round_sec,
  logging_prompt_mode, notes_style, priority
) VALUES (
  ${textLit(r.rule_id)},
  ${textLit(r.program_type)},
  ${intLit(r.schema_version)},
  ${boolLit(r.is_active)},
  ${textLit(r.day_type)},
  ${textLit(r.purpose)},
  ${textLit(r.segment_type)},
  ${textLit(r.movement_pattern)},
  ${textLit(r.swap_group_id_1)},
  ${textLit(r.swap_group_id_2)},
  ${textLit(r.equipment_slug)},
  ${intLit(r.rep_low)},
  ${intLit(r.rep_high)},
  ${textLit(r.reps_unit)},
  ${intLit(r.rir_target)},
  ${intLit(r.rir_min)},
  ${intLit(r.rir_max)},
  ${intLit(r.tempo_eccentric)},
  ${intLit(r.tempo_pause_bottom)},
  ${intLit(r.tempo_concentric)},
  ${intLit(r.tempo_pause_top)},
  ${intLit(r.rest_after_set_sec)},
  ${intLit(r.rest_after_round_sec)},
  ${textLit(r.logging_prompt_mode)},
  ${textLit(r.notes_style)},
  ${intLit(r.priority)}
)
ON CONFLICT (rule_id) DO UPDATE SET
  program_type         = EXCLUDED.program_type,
  schema_version       = EXCLUDED.schema_version,
  is_active            = EXCLUDED.is_active,
  day_type             = EXCLUDED.day_type,
  purpose              = EXCLUDED.purpose,
  segment_type         = EXCLUDED.segment_type,
  movement_pattern     = EXCLUDED.movement_pattern,
  swap_group_id_1      = EXCLUDED.swap_group_id_1,
  swap_group_id_2      = EXCLUDED.swap_group_id_2,
  equipment_slug       = EXCLUDED.equipment_slug,
  rep_low              = EXCLUDED.rep_low,
  rep_high             = EXCLUDED.rep_high,
  reps_unit            = EXCLUDED.reps_unit,
  rir_target           = EXCLUDED.rir_target,
  rir_min              = EXCLUDED.rir_min,
  rir_max              = EXCLUDED.rir_max,
  tempo_eccentric      = EXCLUDED.tempo_eccentric,
  tempo_pause_bottom   = EXCLUDED.tempo_pause_bottom,
  tempo_concentric     = EXCLUDED.tempo_concentric,
  tempo_pause_top      = EXCLUDED.tempo_pause_top,
  rest_after_set_sec   = EXCLUDED.rest_after_set_sec,
  rest_after_round_sec = EXCLUDED.rest_after_round_sec,
  logging_prompt_mode  = EXCLUDED.logging_prompt_mode,
  notes_style          = EXCLUDED.notes_style,
  priority             = EXCLUDED.priority,
  updated_at           = now();`);

  return {
    content: fileHeader("Program Rep Rules", rows.length) + inserts.join("\n\n") + "\n",
    rows: rows.length,
  };
}

async function generateNarrationSnapshot(db) {
  const { rows } = await db.query(`
    SELECT template_id, scope, field, priority, purpose, segment_type,
           applies_json, text_pool_json, is_active, created_at, updated_at
    FROM public.narration_template
    ORDER BY scope, field, priority DESC, template_id
  `);

  const inserts = rows.map((r) => `\
INSERT INTO public.narration_template (
  template_id, scope, field, priority, purpose, segment_type,
  applies_json, text_pool_json, is_active, created_at, updated_at
) VALUES (
  ${textLit(r.template_id)},
  ${textLit(r.scope)},
  ${textLit(r.field)},
  ${intLit(r.priority)},
  ${textLit(r.purpose)},
  ${textLit(r.segment_type)},
  ${jsonbLit(r.applies_json)},
  ${jsonbLit(r.text_pool_json)},
  ${boolLit(r.is_active)},
  ${textLit(r.created_at?.toISOString?.() ?? r.created_at)},
  ${textLit(r.updated_at?.toISOString?.() ?? r.updated_at)}
)
ON CONFLICT (template_id) DO UPDATE SET
  scope         = EXCLUDED.scope,
  field         = EXCLUDED.field,
  priority      = EXCLUDED.priority,
  purpose       = EXCLUDED.purpose,
  segment_type  = EXCLUDED.segment_type,
  applies_json  = EXCLUDED.applies_json,
  text_pool_json = EXCLUDED.text_pool_json,
  is_active     = EXCLUDED.is_active,
  updated_at    = EXCLUDED.updated_at;`);

  return {
    content: fileHeader("Narration Templates", rows.length) + inserts.join("\n\n") + "\n",
    rows: rows.length,
  };
}

// ── File writer ────────────────────────────────────────────────────────────

function writeSnapshot(dir, filename, content) {
  try {
    writeFileSync(join(dir, filename), content, "utf8");
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

function toIsoOrNull(value) {
  if (value === null || value === undefined) return null;
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? null : date.toISOString();
}

export const SYNC_TARGETS = [
  "R__exercise_catalogue_edits.sql",
  "R__seed_program_generation_config.sql",
  "R__seed_program_rep_rules.sql",
  "R__seed_narration_template.sql",
];

export async function buildSyncSnapshots(db = pool) {
  const snapshots = [
    await exportExerciseCatalogueSnapshot(),
    await generatePgcSnapshot(db),
    await generateRepRulesSnapshot(db),
    await generateNarrationSnapshot(db),
  ];
  return snapshots.map((snapshot, i) => ({ file: SYNC_TARGETS[i], ...snapshot }));
}

export function normalizeSnapshot(text) {
  return String(text).replace(/\r\n/g, "\n").split("\n")
    .filter(line => !line.startsWith("-- Generated:")).join("\n");
}

export async function getSyncStatus(db = pool, {
  migrationsDir = MIGRATIONS_DIR,
  buildSnapshots = buildSyncSnapshots,
} = {}) {
  const { rows } = await db.query(`
    SELECT ts FROM admin_audit_log
    WHERE action = 'sync_all_to_flyway'
    ORDER BY ts DESC LIMIT 1
  `);
  const last_synced_at = toIsoOrNull(rows[0]?.ts);
  if (!existsSync(migrationsDir)) {
    return { status: "unavailable", dirty: false, last_synced_at, files: [], changed_files: [],
      message: "Seed files are not present in this environment; sync status is unavailable." };
  }
  const snapshots = await buildSnapshots(db);
  const files = snapshots.map(({ file, content, rows }) => {
    try {
      const disk = readFileSync(join(migrationsDir, file), "utf8");
      return { file, rows, status: normalizeSnapshot(disk) === normalizeSnapshot(content) ? "in_sync" : "changed" };
    } catch (err) {
      return err.code === "ENOENT" ? { file, rows, status: "missing" }
        : { file, rows, status: "error", error: err.message };
    }
  });
  const changed_files = files.filter(f => f.status === "changed" || f.status === "missing").map(f => f.file);
  const errors = files.filter(f => f.status === "error");
  const dirty = changed_files.length > 0;
  return {
    status: errors.length ? "error" : dirty ? "dirty" : "clean",
    dirty, last_synced_at, files, changed_files,
    message: errors.length ? `Could not read one or more seed files: ${errors.map(f => f.file).join(", ")}.`
      : dirty ? `Seed files differ from the database: ${changed_files.join(", ")}. Run 'Sync All to Flyway' to protect your edits.`
      : "Seed files are up to date.",
  };
}

function syncOptions(req) {
  return {
    migrationsDir: req.app?.locals?.migrationsDir ?? MIGRATIONS_DIR,
    buildSnapshots: req.app?.locals?.syncSnapshotBuilder ?? buildSyncSnapshots,
  };
}

adminSyncRouter.get("/sync-status", async (req, res) => {
  try {
    return res.json(await getSyncStatus(req.app?.locals?.pool || pool, syncOptions(req)));
  } catch (err) {
    return res.status(500).json({ ok: false, error: publicInternalError(err) });
  }
});

adminSyncRouter.post("/sync-all-to-flyway", async (req, res) => {
  const results = [];
  let written_count = 0;
  try {
    const db = req.app?.locals?.pool || pool;
    const { migrationsDir, buildSnapshots } = syncOptions(req);
    const audit = req.app?.locals?.syncAuditLog ?? auditLog;
    for (const { file, content, rows } of await buildSnapshots(db)) {
      try {
        const path = join(migrationsDir, file);
        const unchanged = existsSync(path)
          && normalizeSnapshot(readFileSync(path, "utf8")) === normalizeSnapshot(content);
        const result = unchanged ? { ok: true } : writeSnapshot(migrationsDir, file, content);
        const written = result.ok && !unchanged;
        if (written) written_count++;
        results.push({ file, rows, ok: result.ok, written, error: result.error ?? null });
      } catch (err) {
        results.push({ file, rows, ok: false, written: false, error: err.message });
      }
    }
    const ok = results.every(r => r.ok);
    await audit(req, {
      action: "sync_all_to_flyway", entity: "migration_files", entityId: "all", detail: { results },
    });
    return res.status(ok ? 200 : 207).json({ ok, written_count, files: results });
  } catch (err) {
    return res.status(500).json({ ok: false, error: publicInternalError(err), written_count, files: results });
  }
});
