INSERT INTO exercise_catalogue (
  exercise_id,
  name,
  movement_class,
  movement_pattern_primary,
  min_fitness_rank,
  is_archived,
  is_loadable,
  complexity_rank,
  contraindications_json,
  contraindications_slugs,
  density_rating,
  engine_anchor,
  engine_role,
  equipment_items_slugs,
  equipment_json,
  coaching_cues_json,
  impact_level,
  lift_class,
  preferred_in_json,
  load_guidance,
  logging_guidance,
  swap_group_id_1,
  swap_group_id_2,
  target_regions_json,
  warmup_hooks,
  slug,
  creator,
  strength_primary_region,
  strength_equivalent,
  technique_cue,
  technique_setup,
  technique_execution_json,
  technique_mistakes_json,
  technique_video_url,
  load_estimation_metadata
) VALUES (
  'wide_table_rear_delt_row',
  'Wide Table Rear-Delt Row',
  'isolation',
  'pull_horizontal',
  0,
  false,
  false,
  1,
  '[]'::jsonb,
  '{}'::text[],
  2,
  false,
  NULL,
  '{}'::text[],
  '[]'::jsonb,
  '["Take a wide grip under the table edge","Drive elbows wide instead of tucking them","Pause with the upper back engaged"]'::jsonb,
  0,
  NULL,
  '["hypertrophy_accessory","strength_accessory"]'::jsonb,
  NULL,
  NULL,
  'shoulder_iso',
  'rear_delt_accessory',
  '["rear_delts","upper_back"]'::jsonb,
  '["general_heat","t_spine","scap_pull"]'::jsonb,
  NULL,
  '(App admin)',
  'upper',
  false,
  'Drive elbows wide',
  'Set up under a sturdy table with a wide grip and a straight line from shoulders through hips. Keep the ribs stacked and start each rep by reaching long through the shoulders without losing tension.',
  '["Pull the chest toward the table while driving the elbows wide","Pause briefly when the rear delts and upper back are engaged","Lower under control until the arms are long again"]'::jsonb,
  '["Tucking the elbows and turning it into a lat-dominant row","Letting the hips sag or using momentum to finish the rep"]'::jsonb,
  NULL,
  NULL
)
ON CONFLICT (exercise_id) DO UPDATE SET
  name = EXCLUDED.name,
  movement_class = EXCLUDED.movement_class,
  movement_pattern_primary = EXCLUDED.movement_pattern_primary,
  min_fitness_rank = EXCLUDED.min_fitness_rank,
  is_archived = EXCLUDED.is_archived,
  is_loadable = EXCLUDED.is_loadable,
  complexity_rank = EXCLUDED.complexity_rank,
  contraindications_json = EXCLUDED.contraindications_json,
  contraindications_slugs = EXCLUDED.contraindications_slugs,
  density_rating = EXCLUDED.density_rating,
  engine_anchor = EXCLUDED.engine_anchor,
  engine_role = EXCLUDED.engine_role,
  equipment_items_slugs = EXCLUDED.equipment_items_slugs,
  equipment_json = EXCLUDED.equipment_json,
  coaching_cues_json = EXCLUDED.coaching_cues_json,
  impact_level = EXCLUDED.impact_level,
  lift_class = EXCLUDED.lift_class,
  preferred_in_json = EXCLUDED.preferred_in_json,
  load_guidance = EXCLUDED.load_guidance,
  logging_guidance = EXCLUDED.logging_guidance,
  swap_group_id_1 = EXCLUDED.swap_group_id_1,
  swap_group_id_2 = EXCLUDED.swap_group_id_2,
  target_regions_json = EXCLUDED.target_regions_json,
  warmup_hooks = EXCLUDED.warmup_hooks,
  slug = EXCLUDED.slug,
  creator = EXCLUDED.creator,
  strength_primary_region = EXCLUDED.strength_primary_region,
  strength_equivalent = EXCLUDED.strength_equivalent,
  technique_cue = EXCLUDED.technique_cue,
  technique_setup = EXCLUDED.technique_setup,
  technique_execution_json = EXCLUDED.technique_execution_json,
  technique_mistakes_json = EXCLUDED.technique_mistakes_json,
  technique_video_url = EXCLUDED.technique_video_url,
  load_estimation_metadata = EXCLUDED.load_estimation_metadata;
