INSERT INTO exercise_catalogue (
  exercise_id,
  name,
  movement_class,
  movement_pattern_primary,
  min_fitness_rank,
  is_archived,
  is_loadable,
  complexity_rank,
  contraindications_json,
  contraindications_slugs,
  density_rating,
  engine_anchor,
  engine_role,
  equipment_items_slugs,
  equipment_json,
  coaching_cues_json,
  impact_level,
  lift_class,
  preferred_in_json,
  load_guidance,
  logging_guidance,
  swap_group_id_1,
  swap_group_id_2,
  target_regions_json,
  warmup_hooks,
  slug,
  creator,
  strength_primary_region,
  strength_equivalent,
  technique_cue,
  technique_setup,
  technique_execution_json,
  technique_mistakes_json,
  technique_video_url,
  load_estimation_metadata
) VALUES
(
  'pike_shoulder_taps',
  'Pike Shoulder Taps',
  'compound',
  'push_vertical',
  1,
  false,
  false,
  2,
  '[]'::jsonb,
  '{}'::text[],
  2,
  false,
  NULL,
  '{}'::text[],
  '[]'::jsonb,
  '["Keep hips high","Tap without rocking","Press the floor away"]'::jsonb,
  0,
  NULL,
  '["hypertrophy_accessory","strength_accessory"]'::jsonb,
  NULL,
  NULL,
  'shoulder_iso',
  'shoulder_accessory',
  '["shoulders","core","triceps"]'::jsonb,
  '["general_heat","t_spine","shoulders","scap_up"]'::jsonb,
  NULL,
  '(App admin)',
  'upper',
  false,
  'Tap without shifting',
  'Set up in a pike position with hips high, hands planted, and the shoulders stacked over the hands. Brace before the first rep so each tap is controlled rather than a weight shift.',
  '["Press firmly through the support hand while lifting the other hand to tap the opposite shoulder","Keep the hips high and limit torso rotation","Replace the hand under control before alternating sides"]'::jsonb,
  '["Rocking side to side to make the tap easier","Letting the head drop between the shoulders","Turning the movement into a rushed plank tap"]'::jsonb,
  NULL,
  NULL
),
(
  'wall_walk',
  'Wall Walk',
  'compound',
  'push_vertical',
  2,
  false,
  false,
  3,
  '[]'::jsonb,
  '{}'::text[],
  3,
  false,
  NULL,
  '{}'::text[],
  '[]'::jsonb,
  '["Small hand steps","Keep ribs down","Only walk as high as you control"]'::jsonb,
  1,
  NULL,
  '["hypertrophy_accessory","strength_accessory"]'::jsonb,
  NULL,
  NULL,
  'shoulder_iso',
  'shoulder_accessory',
  '["shoulders","core","triceps"]'::jsonb,
  '["general_heat","t_spine","shoulders","scap_up"]'::jsonb,
  NULL,
  '(App admin)',
  'upper',
  false,
  'Small steps, steady brace',
  'Start in a push-up position with feet near a wall. Brace the trunk before the first step and choose a stopping height you can control without arching through the low back.',
  '["Walk the feet up the wall while taking small hand steps toward it","Stop before the ribs flare or the shoulders lose control","Walk back down with the same small steps and finish in a strong plank"]'::jsonb,
  '["Rushing the descent and collapsing into the floor","Overarching the low back near the wall","Walking higher than the shoulders can control"]'::jsonb,
  NULL,
  NULL
)
ON CONFLICT (exercise_id) DO UPDATE SET
  name = EXCLUDED.name,
  movement_class = EXCLUDED.movement_class,
  movement_pattern_primary = EXCLUDED.movement_pattern_primary,
  min_fitness_rank = EXCLUDED.min_fitness_rank,
  is_archived = EXCLUDED.is_archived,
  is_loadable = EXCLUDED.is_loadable,
  complexity_rank = EXCLUDED.complexity_rank,
  contraindications_json = EXCLUDED.contraindications_json,
  contraindications_slugs = EXCLUDED.contraindications_slugs,
  density_rating = EXCLUDED.density_rating,
  engine_anchor = EXCLUDED.engine_anchor,
  engine_role = EXCLUDED.engine_role,
  equipment_items_slugs = EXCLUDED.equipment_items_slugs,
  equipment_json = EXCLUDED.equipment_json,
  coaching_cues_json = EXCLUDED.coaching_cues_json,
  impact_level = EXCLUDED.impact_level,
  lift_class = EXCLUDED.lift_class,
  preferred_in_json = EXCLUDED.preferred_in_json,
  load_guidance = EXCLUDED.load_guidance,
  logging_guidance = EXCLUDED.logging_guidance,
  swap_group_id_1 = EXCLUDED.swap_group_id_1,
  swap_group_id_2 = EXCLUDED.swap_group_id_2,
  target_regions_json = EXCLUDED.target_regions_json,
  warmup_hooks = EXCLUDED.warmup_hooks,
  slug = EXCLUDED.slug,
  creator = EXCLUDED.creator,
  strength_primary_region = EXCLUDED.strength_primary_region,
  strength_equivalent = EXCLUDED.strength_equivalent,
  technique_cue = EXCLUDED.technique_cue,
  technique_setup = EXCLUDED.technique_setup,
  technique_execution_json = EXCLUDED.technique_execution_json,
  technique_mistakes_json = EXCLUDED.technique_mistakes_json,
  technique_video_url = EXCLUDED.technique_video_url,
  load_estimation_metadata = EXCLUDED.load_estimation_metadata;
