export const COUNTRY_REGION_MAP = Object.freeze({
  GBR: "europe",
  GB: "europe",
  "UNITED KINGDOM": "europe",
  UK: "europe",
  IRL: "europe",
  IRELAND: "europe",
  FRA: "europe",
  FRANCE: "europe",
  DEU: "europe",
  GERMANY: "europe",
  NLD: "europe",
  NETHERLANDS: "europe",
  ITA: "europe",
  ITALY: "europe",
  DNK: "europe",
  DENMARK: "europe",
  POL: "europe",
  POLAND: "europe",
  ESP: "europe",
  SPAIN: "europe",
  AUT: "europe",
  AUSTRIA: "europe",
  SWE: "europe",
  SWEDEN: "europe",
  BEL: "europe",
  BELGIUM: "europe",
  CHE: "europe",
  SWITZERLAND: "europe",
  NOR: "europe",
  NORWAY: "europe",
  PRT: "europe",
  PORTUGAL: "europe",
  FIN: "europe",
  FINLAND: "europe",
  CZE: "europe",
  CZECHIA: "europe",
  "CZECH REPUBLIC": "europe",
  HUN: "europe",
  HUNGARY: "europe",
  ROU: "europe",
  ROMANIA: "europe",
  SVK: "europe",
  SLOVAKIA: "europe",
  SVN: "europe",
  SLOVENIA: "europe",
  HRV: "europe",
  CROATIA: "europe",
  BGR: "europe",
  BULGARIA: "europe",
  GRC: "europe",
  GREECE: "europe",
  SRB: "europe",
  SERBIA: "europe",
  LTU: "europe",
  LITHUANIA: "europe",
  LVA: "europe",
  LATVIA: "europe",
  EST: "europe",
  ESTONIA: "europe",

  AUS: "oceania",
  AUSTRALIA: "oceania",
  NZL: "oceania",
  "NEW ZEALAND": "oceania",

  USA: "americas",
  "UNITED STATES": "americas",
  "UNITED STATES OF AMERICA": "americas",
  CAN: "americas",
  CANADA: "americas",
  MEX: "americas",
  MEXICO: "americas",
  BRA: "americas",
  BRAZIL: "americas",
  ARG: "americas",
  ARGENTINA: "americas",
  COL: "americas",
  COLOMBIA: "americas",
  CHL: "americas",
  CHILE: "americas",
  PER: "americas",
  PERU: "americas",
  URY: "americas",
  URUGUAY: "americas",
  ECU: "americas",
  ECUADOR: "americas",
  GTM: "americas",
  GUATEMALA: "americas",

  SGP: "asia",
  SINGAPORE: "asia",
  HKG: "asia",
  "HONG KONG": "asia",
  TWN: "asia",
  TAIWAN: "asia",
  KOR: "asia",
  "SOUTH KOREA": "asia",
  KOREA: "asia",
  JPN: "asia",
  JAPAN: "asia",
  IND: "asia",
  INDIA: "asia",
  THA: "asia",
  THAILAND: "asia",
  MYS: "asia",
  MALAYSIA: "asia",
  IDN: "asia",
  INDONESIA: "asia",
  PHL: "asia",
  PHILIPPINES: "asia",
  CHN: "asia",
  CHINA: "asia",
  VNM: "asia",
  VIETNAM: "asia",

  ZAF: "africa_me",
  "SOUTH AFRICA": "africa_me",
  TUR: "africa_me",
  TURKEY: "africa_me",
  UAE: "africa_me",
  "UNITED ARAB EMIRATES": "africa_me",
  KEN: "africa_me",
  KENYA: "africa_me",
  MAR: "africa_me",
  MOROCCO: "africa_me",
  QAT: "africa_me",
  QATAR: "africa_me",
  SAU: "africa_me",
  "SAUDI ARABIA": "africa_me",
  EGY: "africa_me",
  EGYPT: "africa_me",
});

export const REGION_LABELS = Object.freeze({
  europe: "Europe",
  oceania: "Oceania",
  americas: "Americas",
  asia: "Asia",
  africa_me: "Africa & Middle East",
});

export function countryToRegion(countryCode) {
  if (!countryCode) return null;
  const key = String(countryCode).trim().toUpperCase();
  if (!key) return null;
  return COUNTRY_REGION_MAP[key] ?? null;
}
