import { sendEmail } from "../../services/emailService.js";
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname_runningEmail = dirname(fileURLToPath(import.meta.url));

let FORMA_LOGO_B64 = "";
const FORMA_LOGO_PATHS = [
  "../reports/assets/forma-logo.png",
  "../../../../web/src/assets/forma-logo.png",
];
for (const relativeLogoPath of FORMA_LOGO_PATHS) {
  try {
    const logoPath = resolve(__dirname_runningEmail, relativeLogoPath);
    FORMA_LOGO_B64 = `data:image/png;base64,${readFileSync(logoPath).toString("base64")}`;
    break;
  } catch {
    // Try the next bundled logo path; header falls back to text mark if none load.
  }
}

const FORMA_MASTHEAD_ASPECT_RATIO = 401 / 70;
const FORMA_BRAND_BLUE = "#00a3f5";

function formaLogoMark(size = 36) {
  const width = Math.round(size * FORMA_MASTHEAD_ASPECT_RATIO);
  if (FORMA_LOGO_B64) {
    return `<img src="${FORMA_LOGO_B64}" alt="Forma — Measure. Understand. Improve." width="${width}" height="${size}" style="width:${width}px;height:${size}px;display:block;" />`;
  }
  return `<span style="display:inline-flex;align-items:center;gap:${Math.round(size * 0.2)}px;">
    <span style="background:${FORMA_BRAND_BLUE};width:${size}px;height:${size}px;border-radius:8px;display:inline-flex;align-items:center;justify-content:center;font-weight:800;color:#fff;font-size:${Math.round(size * 0.44)}px;">F</span>
    <span style="font-size:${Math.round(size * 0.55)}px;font-weight:700;color:#f8fafc;">FORMA</span>
  </span>`;
}

function formatTime(seconds) {
  if (!seconds || seconds <= 0) return "—";
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const pad = (n) => String(n).padStart(2, "0");
  if (h > 0) return `${h}:${pad(m)}:${pad(s)}`;
  return `${m}:${pad(s)}`;
}

function recencyLabel(recency) {
  const map = {
    current: "Current",
    within_6_months: "Within 6 months",
    "6_18_months": "6–18 months ago",
    historic: "Historical",
  };
  return map[recency] ?? recency;
}

function impactColour(impact) {
  if (impact === "high") return "#ef4444";
  if (impact === "medium") return "#f59e0b";
  return "#22d3ee";
}

function impactStyle(impact) {
  return `color:${impactColour(impact)};font-weight:600;font-size:12px;text-transform:uppercase;`;
}

function scoreBar(score) {
  if (score == null) return "—";
  const pct = Math.max(0, Math.min(100, score));
  const colour = pct >= 70 ? "#22c55e" : pct >= 45 ? "#f59e0b" : "#ef4444";
  return `<span style="color:${colour};font-weight:700;">${pct}</span>/100`;
}

export async function sendRunningProfilerEmail(submission, analysis, _db) {
  const { confidence, analysis: a } = analysis;
  const name = submission.display_name ?? submission.email?.split("@")[0] ?? "Athlete";
  const performances = submission.performances ?? [];

  const subject = "Your Running & Hybrid Performance Profile";

  // ─── Plain text ───────────────────────────────────────────────────────────
  const text = [
    `FORMA — Running & Hybrid Performance Profile`,
    ``,
    `Hi ${name},`,
    ``,
    `Your analysis is complete. Here's your Running & Hybrid Performance Profile.`,
    `Confidence: ${confidence.toUpperCase()}`,
    ``,
    `═══ PERFORMANCE SNAPSHOT ═══`,
    ...performances.map((p) => `  ${p.distance.toUpperCase()}: ${formatTime(p.time_seconds)} [${recencyLabel(p.recency)}]`),
    ``,
    `KEY INSIGHT`,
    a.keyInsight,
    ``,
    `═══ PERFORMANCE SCORES ═══`,
    `  Overall:              ${a.overallPerformanceScore}/100`,
    `  Running Capacity:     ${a.runningCapacityScore}/100`,
    `  Strength & Power:     ${a.strengthPowerScore != null ? `${a.strengthPowerScore}/100` : "—"}`,
    `  Endurance Durability: ${a.enduranceDurabilityScore != null ? `${a.enduranceDurabilityScore}/100` : "—"}`,
    `  Running Economy:      ${a.runningEconomyScore != null ? `${a.runningEconomyScore}/100` : "—"}`,
    `  Balance Score:        ${a.balanceScore}/100`,
    ``,
    `═══ PERFORMANCE TRANSLATION ═══`,
    a.performanceTranslation.projectedHyroxSeconds
      ? `Projected HYROX: ${formatTime(a.performanceTranslation.projectedHyroxSeconds)}`
      : "No HYROX projection available.",
    a.performanceTranslation.runningCapacityForGoal
      ? `Running capacity for goal: ${a.performanceTranslation.runningCapacityForGoal}`
      : "",
    `Note: ${a.performanceTranslation.note}`,
    ``,
    `═══ BALANCE & TRADE-OFFS ═══`,
    a.tradeOffOutlook,
    ``,
    `═══ TOP RECOMMENDATIONS ═══`,
    ...a.recommendations.map(
      (r, i) =>
        `${i + 1}. ${r.title} [Impact: ${r.impact.toUpperCase()}]\n   ${r.why}\n   Example: ${r.example}`,
    ),
    ``,
    `─────────────────────────────────────────`,
    `This report was generated by Forma. It is for performance guidance only — not medical or clinical advice.`,
    ``,
  ].join("\n");

  // ─── HTML ─────────────────────────────────────────────────────────────────
  const html = `
<!doctype html>
<html><head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;background:#03070d;font-family:Inter,ui-sans-serif,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center" style="padding:32px 16px;">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;background:#07111f;border-radius:18px;overflow:hidden;border:1px solid rgba(148,163,184,0.18);">

  <!-- Header -->
  <tr><td style="padding:28px 32px;background:linear-gradient(135deg,#07111f,#0a1626);border-bottom:1px solid rgba(148,163,184,0.12);">
    <div style="display:flex;align-items:center;">
      ${formaLogoMark(36)}
    </div>
    <h1 style="margin:20px 0 4px;font-size:24px;font-weight:800;color:#f8fafc;">Running &amp; Hybrid Performance Profile</h1>
    <p style="margin:0;font-size:13px;color:#64748b;">Confidence: <span style="color:${confidence === "high" ? "#22c55e" : confidence === "medium" ? "#f59e0b" : "#ef4444"};font-weight:700;">${confidence.toUpperCase()}</span></p>
  </td></tr>

  <!-- Greeting -->
  <tr><td style="padding:24px 32px;">
    <p style="font-size:16px;color:#cbd5e1;margin:0;">Hi ${name},</p>
    <p style="font-size:14px;color:#94a3b8;margin:8px 0 0;">Your running &amp; hybrid performance profile is ready. Here's what the data says.</p>
  </td></tr>

  <!-- Performance Snapshot -->
  <tr><td style="padding:0 32px 24px;">
    <div style="background:rgba(10,22,38,0.84);border:1px solid rgba(148,163,184,0.18);border-radius:12px;padding:20px;">
      <p style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#64748b;margin:0 0 14px;">Performance Snapshot</p>
      ${performances.map((p) => `
        <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid rgba(148,163,184,0.1);">
          <span style="color:#94a3b8;font-size:14px;">${p.distance.replace(/_/g, " ").toUpperCase()}</span>
          <span style="color:#f8fafc;font-weight:600;font-variant-numeric:tabular-nums;">${formatTime(p.time_seconds)}</span>
          <span style="color:#64748b;font-size:12px;">${recencyLabel(p.recency)}</span>
        </div>`).join("")}
    </div>
  </td></tr>

  <!-- Key Insight -->
  <tr><td style="padding:0 32px 24px;">
    <div style="background:rgba(15,111,255,0.08);border:1px solid rgba(15,111,255,0.25);border-radius:12px;padding:20px;">
      <p style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#22d3ee;margin:0 0 10px;">Key Insight</p>
      <p style="font-size:15px;color:#f8fafc;margin:0;line-height:1.6;">${a.keyInsight}</p>
    </div>
  </td></tr>

  <!-- Scores -->
  <tr><td style="padding:0 32px 24px;">
    <p style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#64748b;margin:0 0 14px;">Performance Scores</p>
    <table width="100%" cellpadding="0" cellspacing="0">
      ${[
        ["Overall Performance", a.overallPerformanceScore],
        ["Running Capacity", a.runningCapacityScore],
        ["Strength & Power", a.strengthPowerScore],
        ["Endurance Durability", a.enduranceDurabilityScore],
        ["Running Economy", a.runningEconomyScore],
        ["Balance Score", a.balanceScore],
      ].map(([label, score]) => score != null ? `
      <tr>
        <td style="padding:6px 0;font-size:13px;color:#94a3b8;">${label}</td>
        <td style="padding:6px 0;text-align:right;">${scoreBar(score)}</td>
      </tr>` : "").join("")}
    </table>
  </td></tr>

  <!-- Performance Translation -->
  ${a.performanceTranslation.projectedHyroxSeconds ? `
  <tr><td style="padding:0 32px 24px;">
    <div style="background:rgba(20,184,166,0.08);border:1px solid rgba(20,184,166,0.2);border-radius:12px;padding:20px;">
      <p style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#14b8a6;margin:0 0 10px;">Performance Translation</p>
      <p style="font-size:22px;font-weight:700;color:#f8fafc;margin:0 0 4px;">Projected HYROX: ${formatTime(a.performanceTranslation.projectedHyroxSeconds)}</p>
      ${a.performanceTranslation.runningCapacityForGoal ? `<p style="font-size:13px;color:#94a3b8;margin:4px 0 0;">Running capacity for target: <span style="color:#f8fafc;font-weight:600;">${a.performanceTranslation.runningCapacityForGoal}</span></p>` : ""}
      <p style="font-size:12px;color:#64748b;margin:10px 0 0;">${a.performanceTranslation.note}</p>
    </div>
  </td></tr>` : ""}

  <!-- Trade-offs -->
  <tr><td style="padding:0 32px 24px;">
    <div style="background:rgba(10,22,38,0.84);border:1px solid rgba(148,163,184,0.18);border-radius:12px;padding:20px;">
      <p style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#64748b;margin:0 0 10px;">Balance &amp; Trade-Offs</p>
      <p style="font-size:14px;color:#cbd5e1;margin:0;line-height:1.6;">${a.tradeOffOutlook}</p>
    </div>
  </td></tr>

  <!-- Recommendations -->
  <tr><td style="padding:0 32px 24px;">
    <p style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#64748b;margin:0 0 14px;">Top Recommendations</p>
    ${a.recommendations.map((r, i) => `
    <div style="margin-bottom:12px;padding:16px;background:rgba(14,31,52,0.82);border:1px solid rgba(148,163,184,0.18);border-radius:12px;">
      <div style="display:flex;justify-content:space-between;margin-bottom:8px;">
        <span style="font-size:14px;font-weight:700;color:#f8fafc;">${i + 1}. ${r.title}</span>
        <span style="${impactStyle(r.impact)}">${r.impact}</span>
      </div>
      <p style="font-size:13px;color:#94a3b8;margin:0 0 8px;line-height:1.5;">${r.why}</p>
      <p style="font-size:12px;color:#64748b;margin:0;"><strong style="color:#94a3b8;">Example:</strong> ${r.example}</p>
    </div>`).join("")}
  </td></tr>

  <!-- Footer -->
  <tr><td style="padding:24px 32px;background:rgba(3,7,13,0.6);border-top:1px solid rgba(148,163,184,0.1);">
    <p style="font-size:12px;color:#64748b;margin:0;line-height:1.6;">
      This report is for performance guidance only. It is not medical or clinical advice.<br>
      Generated by <strong style="color:#94a3b8;">Forma — Measure. Understand. Improve.</strong>
    </p>
  </td></tr>

</table>
</td></tr>
</table>
</body>
</html>`.trim();

  await sendEmail({ to: submission.email, subject, text, html });
}
